(cl:defpackage pick_delivery-srv
  (:use )
  (:export
   "INVIO"
   "<INVIO-REQUEST>"
   "INVIO-REQUEST"
   "<INVIO-RESPONSE>"
   "INVIO-RESPONSE"
   "LOGIN"
   "<LOGIN-REQUEST>"
   "LOGIN-REQUEST"
   "<LOGIN-RESPONSE>"
   "LOGIN-RESPONSE"
   "NOTIFICA"
   "<NOTIFICA-REQUEST>"
   "NOTIFICA-REQUEST"
   "<NOTIFICA-RESPONSE>"
   "NOTIFICA-RESPONSE"
  ))

