// Generated by gencpp from file pick_delivery/invioResponse.msg
// DO NOT EDIT!


#ifndef PICK_DELIVERY_MESSAGE_INVIORESPONSE_H
#define PICK_DELIVERY_MESSAGE_INVIORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pick_delivery
{
template <class ContainerAllocator>
struct invioResponse_
{
  typedef invioResponse_<ContainerAllocator> Type;

  invioResponse_()
    : serv_resp(0)  {
    }
  invioResponse_(const ContainerAllocator& _alloc)
    : serv_resp(0)  {
  (void)_alloc;
    }



   typedef int64_t _serv_resp_type;
  _serv_resp_type serv_resp;





  typedef boost::shared_ptr< ::pick_delivery::invioResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_delivery::invioResponse_<ContainerAllocator> const> ConstPtr;

}; // struct invioResponse_

typedef ::pick_delivery::invioResponse_<std::allocator<void> > invioResponse;

typedef boost::shared_ptr< ::pick_delivery::invioResponse > invioResponsePtr;
typedef boost::shared_ptr< ::pick_delivery::invioResponse const> invioResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_delivery::invioResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_delivery::invioResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pick_delivery::invioResponse_<ContainerAllocator1> & lhs, const ::pick_delivery::invioResponse_<ContainerAllocator2> & rhs)
{
  return lhs.serv_resp == rhs.serv_resp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pick_delivery::invioResponse_<ContainerAllocator1> & lhs, const ::pick_delivery::invioResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pick_delivery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pick_delivery::invioResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_delivery::invioResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_delivery::invioResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_delivery::invioResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_delivery::invioResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_delivery::invioResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_delivery::invioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e72a2e640338b0dea77e035e6c49733";
  }

  static const char* value(const ::pick_delivery::invioResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e72a2e640338b0dULL;
  static const uint64_t static_value2 = 0xea77e035e6c49733ULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_delivery::invioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_delivery/invioResponse";
  }

  static const char* value(const ::pick_delivery::invioResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_delivery::invioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 serv_resp\n"
;
  }

  static const char* value(const ::pick_delivery::invioResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_delivery::invioResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.serv_resp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct invioResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_delivery::invioResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_delivery::invioResponse_<ContainerAllocator>& v)
  {
    s << indent << "serv_resp: ";
    Printer<int64_t>::stream(s, indent + "  ", v.serv_resp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_DELIVERY_MESSAGE_INVIORESPONSE_H
