// Generated by gencpp from file pick_delivery/login.msg
// DO NOT EDIT!


#ifndef PICK_DELIVERY_MESSAGE_LOGIN_H
#define PICK_DELIVERY_MESSAGE_LOGIN_H

#include <ros/service_traits.h>


#include <pick_delivery/loginRequest.h>
#include <pick_delivery/loginResponse.h>


namespace pick_delivery
{

struct login
{

typedef loginRequest Request;
typedef loginResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct login
} // namespace pick_delivery


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pick_delivery::login > {
  static const char* value()
  {
    return "f832b245f80447f012d2bc11a8aa30b1";
  }

  static const char* value(const ::pick_delivery::login&) { return value(); }
};

template<>
struct DataType< ::pick_delivery::login > {
  static const char* value()
  {
    return "pick_delivery/login";
  }

  static const char* value(const ::pick_delivery::login&) { return value(); }
};


// service_traits::MD5Sum< ::pick_delivery::loginRequest> should match
// service_traits::MD5Sum< ::pick_delivery::login >
template<>
struct MD5Sum< ::pick_delivery::loginRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pick_delivery::login >::value();
  }
  static const char* value(const ::pick_delivery::loginRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_delivery::loginRequest> should match
// service_traits::DataType< ::pick_delivery::login >
template<>
struct DataType< ::pick_delivery::loginRequest>
{
  static const char* value()
  {
    return DataType< ::pick_delivery::login >::value();
  }
  static const char* value(const ::pick_delivery::loginRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pick_delivery::loginResponse> should match
// service_traits::MD5Sum< ::pick_delivery::login >
template<>
struct MD5Sum< ::pick_delivery::loginResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pick_delivery::login >::value();
  }
  static const char* value(const ::pick_delivery::loginResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_delivery::loginResponse> should match
// service_traits::DataType< ::pick_delivery::login >
template<>
struct DataType< ::pick_delivery::loginResponse>
{
  static const char* value()
  {
    return DataType< ::pick_delivery::login >::value();
  }
  static const char* value(const ::pick_delivery::loginResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PICK_DELIVERY_MESSAGE_LOGIN_H
