// Generated by gencpp from file pick_delivery/loginRequest.msg
// DO NOT EDIT!


#ifndef PICK_DELIVERY_MESSAGE_LOGINREQUEST_H
#define PICK_DELIVERY_MESSAGE_LOGINREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pick_delivery
{
template <class ContainerAllocator>
struct loginRequest_
{
  typedef loginRequest_<ContainerAllocator> Type;

  loginRequest_()
    : name()
    , aula()
    , type_service(0)  {
    }
  loginRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , aula(_alloc)
    , type_service(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _aula_type;
  _aula_type aula;

   typedef int64_t _type_service_type;
  _type_service_type type_service;





  typedef boost::shared_ptr< ::pick_delivery::loginRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_delivery::loginRequest_<ContainerAllocator> const> ConstPtr;

}; // struct loginRequest_

typedef ::pick_delivery::loginRequest_<std::allocator<void> > loginRequest;

typedef boost::shared_ptr< ::pick_delivery::loginRequest > loginRequestPtr;
typedef boost::shared_ptr< ::pick_delivery::loginRequest const> loginRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_delivery::loginRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_delivery::loginRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pick_delivery::loginRequest_<ContainerAllocator1> & lhs, const ::pick_delivery::loginRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.aula == rhs.aula &&
    lhs.type_service == rhs.type_service;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pick_delivery::loginRequest_<ContainerAllocator1> & lhs, const ::pick_delivery::loginRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pick_delivery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pick_delivery::loginRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_delivery::loginRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_delivery::loginRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_delivery::loginRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_delivery::loginRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_delivery::loginRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_delivery::loginRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "471c4d869261b4a263a94ce694fdb96d";
  }

  static const char* value(const ::pick_delivery::loginRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x471c4d869261b4a2ULL;
  static const uint64_t static_value2 = 0x63a94ce694fdb96dULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_delivery::loginRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_delivery/loginRequest";
  }

  static const char* value(const ::pick_delivery::loginRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_delivery::loginRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string aula\n"
"int64 type_service\n"
;
  }

  static const char* value(const ::pick_delivery::loginRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_delivery::loginRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.aula);
      stream.next(m.type_service);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct loginRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_delivery::loginRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_delivery::loginRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "aula: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.aula);
    s << indent << "type_service: ";
    Printer<int64_t>::stream(s, indent + "  ", v.type_service);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_DELIVERY_MESSAGE_LOGINREQUEST_H
