// Generated by gencpp from file pick_delivery/notificaRequest.msg
// DO NOT EDIT!


#ifndef PICK_DELIVERY_MESSAGE_NOTIFICAREQUEST_H
#define PICK_DELIVERY_MESSAGE_NOTIFICAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pick_delivery
{
template <class ContainerAllocator>
struct notificaRequest_
{
  typedef notificaRequest_<ContainerAllocator> Type;

  notificaRequest_()
    : user()
    , auladest()
    , msg()  {
    }
  notificaRequest_(const ContainerAllocator& _alloc)
    : user(_alloc)
    , auladest(_alloc)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _user_type;
  _user_type user;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _auladest_type;
  _auladest_type auladest;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::pick_delivery::notificaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_delivery::notificaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct notificaRequest_

typedef ::pick_delivery::notificaRequest_<std::allocator<void> > notificaRequest;

typedef boost::shared_ptr< ::pick_delivery::notificaRequest > notificaRequestPtr;
typedef boost::shared_ptr< ::pick_delivery::notificaRequest const> notificaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_delivery::notificaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_delivery::notificaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pick_delivery::notificaRequest_<ContainerAllocator1> & lhs, const ::pick_delivery::notificaRequest_<ContainerAllocator2> & rhs)
{
  return lhs.user == rhs.user &&
    lhs.auladest == rhs.auladest &&
    lhs.msg == rhs.msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pick_delivery::notificaRequest_<ContainerAllocator1> & lhs, const ::pick_delivery::notificaRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pick_delivery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pick_delivery::notificaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_delivery::notificaRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_delivery::notificaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_delivery::notificaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_delivery::notificaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_delivery::notificaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_delivery::notificaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "40c9053b48755e02cc19c6f52dd2cd70";
  }

  static const char* value(const ::pick_delivery::notificaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x40c9053b48755e02ULL;
  static const uint64_t static_value2 = 0xcc19c6f52dd2cd70ULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_delivery::notificaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_delivery/notificaRequest";
  }

  static const char* value(const ::pick_delivery::notificaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_delivery::notificaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string user\n"
"string auladest\n"
"string msg\n"
;
  }

  static const char* value(const ::pick_delivery::notificaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_delivery::notificaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user);
      stream.next(m.auladest);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct notificaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_delivery::notificaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_delivery::notificaRequest_<ContainerAllocator>& v)
  {
    s << indent << "user: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.user);
    s << indent << "auladest: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.auladest);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_DELIVERY_MESSAGE_NOTIFICAREQUEST_H
