// Generated by gencpp from file pick_delivery/notifica.msg
// DO NOT EDIT!


#ifndef PICK_DELIVERY_MESSAGE_NOTIFICA_H
#define PICK_DELIVERY_MESSAGE_NOTIFICA_H

#include <ros/service_traits.h>


#include <pick_delivery/notificaRequest.h>
#include <pick_delivery/notificaResponse.h>


namespace pick_delivery
{

struct notifica
{

typedef notificaRequest Request;
typedef notificaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct notifica
} // namespace pick_delivery


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pick_delivery::notifica > {
  static const char* value()
  {
    return "b3820e35b2fce1d8d4821fc34321f691";
  }

  static const char* value(const ::pick_delivery::notifica&) { return value(); }
};

template<>
struct DataType< ::pick_delivery::notifica > {
  static const char* value()
  {
    return "pick_delivery/notifica";
  }

  static const char* value(const ::pick_delivery::notifica&) { return value(); }
};


// service_traits::MD5Sum< ::pick_delivery::notificaRequest> should match
// service_traits::MD5Sum< ::pick_delivery::notifica >
template<>
struct MD5Sum< ::pick_delivery::notificaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pick_delivery::notifica >::value();
  }
  static const char* value(const ::pick_delivery::notificaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_delivery::notificaRequest> should match
// service_traits::DataType< ::pick_delivery::notifica >
template<>
struct DataType< ::pick_delivery::notificaRequest>
{
  static const char* value()
  {
    return DataType< ::pick_delivery::notifica >::value();
  }
  static const char* value(const ::pick_delivery::notificaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pick_delivery::notificaResponse> should match
// service_traits::MD5Sum< ::pick_delivery::notifica >
template<>
struct MD5Sum< ::pick_delivery::notificaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pick_delivery::notifica >::value();
  }
  static const char* value(const ::pick_delivery::notificaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_delivery::notificaResponse> should match
// service_traits::DataType< ::pick_delivery::notifica >
template<>
struct DataType< ::pick_delivery::notificaResponse>
{
  static const char* value()
  {
    return DataType< ::pick_delivery::notifica >::value();
  }
  static const char* value(const ::pick_delivery::notificaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PICK_DELIVERY_MESSAGE_NOTIFICA_H
