// Generated by gencpp from file pick_delivery/s_to_c.msg
// DO NOT EDIT!


#ifndef PICK_DELIVERY_MESSAGE_S_TO_C_H
#define PICK_DELIVERY_MESSAGE_S_TO_C_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pick_delivery
{
template <class ContainerAllocator>
struct s_to_c_
{
  typedef s_to_c_<ContainerAllocator> Type;

  s_to_c_()
    : user()
    , auladest()
    , msg()
    , pd(0)
    , idrob(0)  {
    }
  s_to_c_(const ContainerAllocator& _alloc)
    : user(_alloc)
    , auladest(_alloc)
    , msg(_alloc)
    , pd(0)
    , idrob(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _user_type;
  _user_type user;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _auladest_type;
  _auladest_type auladest;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;

   typedef int64_t _pd_type;
  _pd_type pd;

   typedef int64_t _idrob_type;
  _idrob_type idrob;





  typedef boost::shared_ptr< ::pick_delivery::s_to_c_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_delivery::s_to_c_<ContainerAllocator> const> ConstPtr;

}; // struct s_to_c_

typedef ::pick_delivery::s_to_c_<std::allocator<void> > s_to_c;

typedef boost::shared_ptr< ::pick_delivery::s_to_c > s_to_cPtr;
typedef boost::shared_ptr< ::pick_delivery::s_to_c const> s_to_cConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_delivery::s_to_c_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_delivery::s_to_c_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pick_delivery::s_to_c_<ContainerAllocator1> & lhs, const ::pick_delivery::s_to_c_<ContainerAllocator2> & rhs)
{
  return lhs.user == rhs.user &&
    lhs.auladest == rhs.auladest &&
    lhs.msg == rhs.msg &&
    lhs.pd == rhs.pd &&
    lhs.idrob == rhs.idrob;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pick_delivery::s_to_c_<ContainerAllocator1> & lhs, const ::pick_delivery::s_to_c_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pick_delivery

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pick_delivery::s_to_c_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_delivery::s_to_c_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_delivery::s_to_c_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_delivery::s_to_c_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_delivery::s_to_c_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_delivery::s_to_c_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_delivery::s_to_c_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb7137b9ac77ab1fa8d9494c16204bbe";
  }

  static const char* value(const ::pick_delivery::s_to_c_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb7137b9ac77ab1fULL;
  static const uint64_t static_value2 = 0xa8d9494c16204bbeULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_delivery::s_to_c_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_delivery/s_to_c";
  }

  static const char* value(const ::pick_delivery::s_to_c_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_delivery::s_to_c_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string user\n"
"string auladest\n"
"string msg\n"
"int64 pd\n"
"int64 idrob\n"
;
  }

  static const char* value(const ::pick_delivery::s_to_c_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_delivery::s_to_c_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user);
      stream.next(m.auladest);
      stream.next(m.msg);
      stream.next(m.pd);
      stream.next(m.idrob);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct s_to_c_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_delivery::s_to_c_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_delivery::s_to_c_<ContainerAllocator>& v)
  {
    s << indent << "user: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.user);
    s << indent << "auladest: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.auladest);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
    s << indent << "pd: ";
    Printer<int64_t>::stream(s, indent + "  ", v.pd);
    s << indent << "idrob: ";
    Printer<int64_t>::stream(s, indent + "  ", v.idrob);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_DELIVERY_MESSAGE_S_TO_C_H
